/*def COLOR_MAP [
    'SUCCESS': 'good',
    'FAILURE': 'danger',
]*/
pipeline {
    agent any
    tools {
        maven "MAVEN3"
        jdk "OracleJDK8"
    }
    
    environment {
        cluster = "vproprod"
        service = "vproappprodsvc"
    }

    stages {        
        stage('Deploy to ECS prod') {
            steps {
                withAWS(credentials: 'awscreds', region: 'us-east-2') {
                    sh 'aws ecs update-service --cluster ${cluster} --service ${service} --force-new-deployment'
                } 
            }
        }
    }

    /*post {
        always {
            echo 'Slack Notifications'
            slackSend channel: '#jenkinscicd',
                colo: COLOR_MAP[currentBuild.currentResult],
                message: "*${currentBuild.currentResult}:* Job ${env.JOB_NAME} build ${env.BUILD_NUMBER}"
        }
    }*/
}
